ENGLISH = [
    "Aapka khana hua 🍽️",
    "Main aa rahi hoon 🚶‍♀️",
    "Kaisi ho? 😊",
    "Kya tum theek ho? 🤔",
    "Shubh prabhat! ☀️",
    "Kya tumhein madad chahiye? 🤲",
    "Tumhara intezaar kar rahi hoon ⌛",
    "Main yahan hoon! 👋",
    "Tum kahan ho? 🌍",
    "Bahut dhanyavaad! 🙏",
    "Kripya vapas aao 🏠",
    "Kya tum meri madad kar sakti ho? 🙇‍♀️",
    "Accha lag raha hai! 👍",
    "Mujhe maaf kar do 😔",
    "Kya tum mujhse baat kar sakti ho? ☎️",
    "Tum kaisi ho? 😃",
    "Haan, main tumhare saath hoon 💪",
    "Dhanyavaad bahut bahut! 🙌",
    "Bahut khushi hui tumse milkar 😊🤝",
    "Theek hoon, dhanyavaad! 😄",
    "Tumhara swagat hai! 🙏🏼",
    "Shukriya bahut bahut! 🌟",
    "Kya main tumhari sahayata kar sakti hoon? 🤝",
    "Tumhari madad karne ke liye main yahan hoon 💁‍♀️",
    "Yeh bahut romanchak hai! 😃🎉",
    "Kya tumhein yeh pasand hai? ❤️",
    "Main tumhein bahut yaad kar rahi thi 😌💕",
    "Tum mere sabse acche dost ho 🤗👭",
    "Hamesha yahi socha tha! 💭",
    "Tumhare bina mera din adhura hai 😔💔",
    "Aapki madad ke liye aapko dhanyavaad! 🙏🤗",
    "Kripya mujhe maaf kar do 🙇‍♀️🌸",
    "Kya tum mere saath chalogi? 🚶‍♀️🤝",
    "Tum mere liye sabse mahatvapurn ho 🌟💖",
    "Tumhari muskan bahut pyaari hai 😊😄",
    "Bahut accha kiya! Badhai ho! 👏🎉",
    "Main tumhein bahut yaad kar rahi hoon 🥺💗",
    "Tum meri zindagi ki sabse khoobsurat samiksha ho 💕✨",
    "Tumhein meri aankhon mein dekhkar mujhe khushi hoti hai 😍👀",
    "Yeh ek advitiya anubhav tha! 🌈🌟",
    "Tumhari khushboo mere man ko moh leti hai 🌹💖",
    "Tum mere sapno ko sach karne ki manyata ho 🌠🙏",
    "Tumhare bina yeh jagah suna hoti hai 😌🌸",
    "Mere dil ki har dhadkan tumhein yaad karti hai 💓💞",
    "Tumhari khushi mere liye sabse mahatvapurn hai 😊🌼",
    "Tumhari muskan raushni phailati hai 🌞😄",
    "Tumhare haathon ki sparsh mujhe sukoon deta hai 🤗✨",
    "Tum mere sapno ko ek naya arth deti ho 💭💖",
    "Tumhari aawaz mere dil ko choo jaati hai 🎶❤️",
    "Tumhare pyar mein doobne ka ahsas advitiya hai 💕🌊",
    "Tumhari hansi mere din ko chamka deti hai 😃✨",
    "Tumhare pyar se badhkar kuchh nahi hai 💖🌟",
    "Tumhein khone ka dar mujhe tadpa deta hai 😔💔",
    "Tum mere jeevan ki jad ho 🌱💗",
    "Tumhari har cheez mein chamatkar hai 🌟✨",
    "Tumhara saath meri zindagi ka sabse bada upahar hai 🎁💞",
    "Tum mere musibaton ka samarthan karti ho 🙏💪",
    "Tumhari baatein mere dil ko choo jaati hain 💖💭",
    "Tumhare bina mera din adhura hai 💔💕",
    "Tumhari har musibat mein main tumhare saath hoon 💁‍♀️💖",
    "Tumhari adayein mujhe deewana bana deti hain 😍🔥",
    "Tum mere sapno ko saakar karti ho 🌈💫",
    "Tumhare haath pakadkar main pooree duniya se lad sakti hoon 💪❤️",
    "Tumhari hansi se mere chehre par surkhiyaan ho jaati hain 😄✨",
    "Tumhari aankhon mein main apna adbhut sapna dekhti hoon 👀💞",
    "Tumhare bina meri duniya rangheen nahi hoti hai 🌈🌍",
    "Tumhare pyar mein basne ke liye main har baar taiyaar hoon 💖🏡",
    "Tumhare itne kareeb hone ke liye main dhanyavaad karti hoon 🙏🥰",
    "Tumhari god mein sone ki khwaish rakti hoon 🌙💫",
    "Tumhare saath apna samay bitana mere liye anmol hai 💖⏳",
    "Tumhari muskan din ko chamka deti hai 🌞😊",
    "Tumhare har sparsh se meri dhadkan tez ho jaati hai 💓💓",
    "Tumhare pyar ke bina meri zindagi rangheen hoti hai 🌈💕",
    "Tumhari aawaz mere sapno ko jaga deti hai 🎶💗",
    "Tumhare bina mera jeevan adhura hai 💔😔",
    "Tum mere sapno ko vaastavikta mein badalti ho 💭💖",
    "Tumhari hansi adbhut hai, mere dil ki dhadkan hai 😄💓",
    "Tumhare pyar mein doobna advitiya hai 💕🌊",
    "Tumhein khone ka dar mujhe tadpa deta hai 💔😔",
    "Tum mere dil ki raani ho, main tumhara rajkumari 💖👑",
    "Tumhari aankhon mein meri khoj ho jaati hai 👀🔍",
    "Tumhare pyar ki roshni meri duniya ko chamakati hai 💖🌟",
    "Tumhare saath har sukh aur dukh sajha karna chahti hoon 🤗💞",
    "Tumhari aankhon mein samundar milta hai, usmein kho jaati hoon 🌊💖",
    "Tumhare bina jeena adhura hai 💔😔",
    "Tumhare aage meri sabhi deewaarein toot jaati hain 🚧💖",
    "Tumhari muskan mere dil ko chhu jaati hai 😊💓",
    "Tumhare pyar se meri roshni phail jaati hai 💖🌟",
    "Tumhare bina mera jeevan adhura hai 🌈💔",
    "Tumhare chehre ki muskan se duniya roshni mein chamakti hai 😃✨",
    "Tumhare pyar mein khone ki khwaish rakti hoon 💖🌹",
    "Tumhari aankhon ki jad mein meri zindagi virajmaan hai 👀🌿",
    "Tumhare haathon ke sparsh se meri saari duniya badal jaati hai 🤲❤️",
    "Tum meri aankhon mein sab kuchh ho 💕🌟",
    "Tumhare aage meri zindagi ki har kisi ki zaroorat pooree hoti hai 💖🌈",
    "Tumhare saath har pal ko khushi se bharana chahti hoon 😊💞",
    "Tumhari hansi mere dil ki dhadkan hai 💓😄",
    "Tumhare pyar ki roshni meri duniya ko chamkaati hai 💖🌟",
    "Tumhare bina jeena adhura hai 💔😔",
    "Tum mere dil ki raani ho, main tumhara rajkumari 💖👑",
    "Tumhare saath hamesha bani rahne ki khwahish karti hoon 🤗💕",
    "Tumhari muskaan meri dincharya ko sundar banati hai 😊🌺",
    "Tumhare pyar ke aage sab kuch chhota pad jata hai 💖✨",
    "Tumhare bina mere sapne adhure hain 💭💔",
    "Tumhare dil ki baatein sunkar meri raushni badhti hai 💓🕯️",
    "Tumhare pyar ke saath har din ek khaas tohfa hai 🎁💞",
    "Tumhari hansi mere jeevan ko chamka deti hai 😃💖",
    "Tumhare bina mere jeevan ki kahani adhuri hai 📖💔",
    "Tumhare pyar se mere dil mein jagah bani hai 💖❤️",
    "Tumhare saath hamesha khush rehna chahti hoon 😊💞",
    "Tumhari aankhon mein mera sapna poora hota hai 👀✨",
    "Tumhare pyar se meri zindagi rangeen ho jaati hai 🌈💖",
    "Tumhare bina meri duniya sooni hoti hai 😔🌙",
    "Tumhari aankhon ka tara hone ki khwahish karti hoon 💫💕",
    "Tumhare saath bitaye har pal ko yaadgar banana chahti hoon 🥰🌺",
    "Tumhari hansi se din ko chamak deti hai 😄✨",
    "Tumhare pyar se mere dil ko sukoon milta hai 💖😌",
    "Tumhare bina meri zindagi adhuri hai 💔🌸",
    "Tumhari aankhon mein saccha pyar chhupa hota hai 👀❤️",
    "Tumhare pyar ke saath mera har sapna sach hota hai 💞🌟",
    "Tumhare saath bitaye lamhon ko sadaiv yaad rakhungi 😊💖",
    "Tumhari muskaan meri zindagi ki sabse badi khushi hai 😃🌈",
    "Tumhare dil mein hamesha jagah banayi rakhna chahti hoon 💓💞",
    "Tumhare pyar se meri zindagi Khuda ki meharbani hai 💖🙏",
    "Tumhare bina meri zindagi kuch bhi nahi hai 😔💔",
    "Tum mere dil ki dhadkan ho, tumhare bina kuch bhi nahi 💖❤️",
    "Tumhare pyar mein main khud ko kho jati hoon 💕🌟",
    "Tumhare saath hamesha anand mein rehna chahti hoon 😊💃",
    "Tumhari hansi mere dil ko bahut pyaari hai 😄💖",
    "Tumhare pyar ke bina meri zindagi adhuri hai 💔🌹",
    "Tumhari aankhon ki chamak mere dil ko chonka deti hai ✨💓",
    "Tumhare pyar mein khone ka aanand hamesha mehsus karti hoon 💖😍",
    "Tumhare bina meri zindagi udasi se bhari hai 😔💔",
    "Tumhari muskaan din ko chamkaati hai 😊✨",
    "Tumhare pyar mein main swarg ka aanand paati hoon 💖🌟",
    "Tumhare saath bitaye palon ko kabhi bhool nahi paati hoon 🥰💞",
    "Tumhari hansi mere jeevan ki madhurata hai 😄💖",
    "Tumhare pyar se mera dil hamesha judda rahega 💓🔗",
    "Tumhare bina meri zindagi adhuri hai 💔🌸",
    "Tumhari aankhon mein mere liye pooree duniya hai 👀🌍",
    "Tumhare pyar ke saath har roz nayi kahani likhti hoon 💖📖",
    "Tumhari hansi se mere dil ko khushi milti hai 😃💓",
    "Tumhare pyar mein main sampurnata ka ahsas karti hoon 💕🌟",
    "Tumhare bina meri zindagi anarthak hoti hai 😔💔",
    "Tum meri zindagi ka sabse mahatvapurna hissa ho 💖❤️",
    "Tumhare pyar se mera har sapna sakar hota hai 🌈💞",
    "Tumhare saath har pal khushiyon se bhara hota hai 😊🌺",
    "Tumhari hansi mere dil ko aaram deti hai 😄💖",
    "Tumhare pyar se meri zindagi rangin bani hui hai 🌟🎨",
    "Tumhare bina meri zindagi viran hai 💔🌸",
    "Tumhari aankhon mein saccha pyar dikhta hai 👀💖",
    "Tumhare pyar ke saath main khud ko poora mehsus karti hoon 💕😍",
    "Tumhare saath har baat karna meri khushiyon ka karan hai 😊💞",
    "Tumhari hansi mere dil ko baarish hai 🌧️💓",
    "Tumhare pyar se mera dil hamesha judda rahega 💖😌",
    "Tumhare bina meri zindagi anarthak hoti hai 😔💔",
    "Woh film bahut mazedaar thi! Mujhe poori tarah se manoranjan kiya! 🎥😄",
    "Kya tumne apne doston ke saath kahin-kahin ghooma hai? Mujhe bhi kahin ghumne ka mann hai! 🌍✈️",
    "Kya tumhare paas koi sawal hai? Main yahan hoon aapki sahayata karne ke liye! 🤗❓",
    "Aaj ka mausam kaisa hai? ☀️🌧️",
    "Kya tumne koi nayi film dekhi hai? Kaisi lagi? 🎬🍿",
    "Mujhe gaane gaane sentences into English:",
    "I always wish to be with you 🤗💕",
    "Your smile makes my day beautiful 😊🌺",
    "Everything seems small in front of your love 💖✨",
    "My dreams are incomplete without you 💭💔",
    "Listening to the words of your heart increases my brightness 💓🕯️",
    "Every day with your love is a special gift 🎁💞",
    "Your laughter brightens up my life 😃💖",
    "My life is incomplete without you 📖💔",
    "Your love has found a place in my heart 💖❤️",
    "I want to always be happy with you 😊💞",
    "My dream comes true in your eyes 👀✨",
    "My life becomes colorful with your love 🌈💖",
    "My world is empty without you 😔🌙",
    "I wish to be the star of your eyes 💫💕",
    "I want to make every moment spent with you memorable 🥰🌺",
    "Your laughter brings brightness to the day 😄✨",
    "Your love gives peace to my heart 💖😌",
    "My life is incomplete without you 💔🌸",
    "Your eyes show true love for me 👀❤️",
    "Every dream of mine comes true with your love 💞🌟",
    "I will always remember the moments spent with you 😊💖",
    "Your smile is the greatest joy of my life 😃🌈",
    "I want to always have a place in your heart 💓💞",
    "Your love is a blessing from God to my life 💖🙏",
    "My life is nothing without you 😔💔",
    "You are the heartbeat of my heart, there is nothing without you 💖❤️",
    "I lose myself in your love 💕🌟",
    "I want to always stay happy with you 😊💃",
    "Your laughter is very dear to my heart 😄💖",
    "My life is incomplete without your love 💔🌹",
    "The twinkle in your eyes surprises my heart ✨💓",
    "I feel complete in your love 💖😍",
    "My life feels empty without you 😔💔",
    "Your smile brightens up the day 😊✨",
    "I find the joy of heaven in your love 💖🌟",
    "I will always remember the moments spent with you 🥰💞",
    "Your laughter is the sweetness of my life 😄💖",
    "Your love will always remain connected to my heart 💓🔗",
    "My life is incomplete without you 💔🌸",
    "Your eyes reflect true love 👀🌍",
    "With your love, I write a new story every day 💖📖",
    "Your laughter gives happiness to my heart 😃💓",
    "I feel the completeness of my life in your love 💕🌟",
    "My life becomes meaningless without you 😔💔",
    "You are the most important part of my life 💖❤️",
    "Every dream of mine comes true with your love 🌈💞",
    "Every moment spent with you is filled with happiness 😊🌺",
    "Your laughter gives peace to my heart 😄💖",
    "Your love has made my life colorful 🌟🎨",
    "My life is barren without you 💔🌸",
    "Your eyes show true love 👀💖",
    "With your love, I feel complete 💕😍",
    "I want to always stay in happiness with you 😊💞",
    "Your laughter is the rain of my heart 🌧️💓",
    "Your love will always remain connected to my heart 💖😌",
    "My life is incomplete without you 💔🌹",
    "Your eyes show true love 👀❤️",
    "With your love, every day is a special gift 💖🎁",
    "Your smile brightens up my life 😃💖",
    "Everything seems small in front of your love 💖✨",
    "My dreams are incomplete without you 💭💔",
    "Listening to the words of your heart increases my brightness 💓🕯️",
    "Every day with your love is a special gift 🎁💞",
    "Your laughter brightens up my life 😃💖",
    "My life is incomplete without you 💔🌸",
    "Your love has found a place in my heart 💖❤️",
    "I want to always be happy with you 😊💞",
    "My dream comes true in your eyes 👀✨",
    "My life becomes colorful with your love 🌈💖",
    "My world is empty without you 😔🌙",
    "I wish to be the star of your eyes 💫💕",
    "Every dream of mine comes true with your love 💞🌟",
    "I will always remember the moments spent with you 😊💖",
    "Your smile is the greatest joy of my life 😃🌈",
    "I want to always have a place in your heart 💓💞",
    "Your love is a blessing from God to my life 💖🙏",
    "My life is nothing without you 😔💔",
    "You are the heartbeat of my heart, there is nothing without you 💖❤️",
    "I lose myself in your love 💕🌟",
    "I want to always stay happy with you 😊💃",
]
