HARYAANAVI = [
    "Jai Baba Ki",
    "K hall s pardhan",
    "Mkha ram ram tai ale",
    "Tai ale k kra kr",
    "Or ladle tikad pad liye",
    "Mera dabhi bnga",
    "mer t bhi baat krle m k chutke bhru su",
    "Roti khali k",
    " M bhi aau su",
    "K haal chal s" "Or bta sab thik thak",
    "Jai baba ki" "Tn khdi dikkan laag ri su tawal aja",
    "M to ur a su",
    "Tu kit s",
    "Ghana sara balti bhar ki dhanywaad",
    "Ulta aja",
    " Mera ek kaam kr de ",
    "Badiya lag s",
    "Meri galti hogi chod ib baat n",
    "Mer geli baat krgi k",
    "Or suna se mans",
    "Haan, m ter geli su tension na le",
    "Ter t mil ki to jee raji hoga",
    "Aja ib k geet ali bulawa",
    "O teri k yo k sang s",
    "Yo mera ek no ka yadi s",
    "Mer gelya chalga",
]
