PUNJABI = [
    "Tuhada favourite singer ya band kehda hai",
    "Kde bungeejumping ya skydiving try kiti hai",
    "Tuhade lai perfect weekend kive dikhda hai",
    "Kya tuhanu dancing pasand hai",
    "Tuhanu travel krde wqt kya kya essentials pack karne hunde hai",
    "Kya tusi kde adventure sports try karna chahde ho",
    "Tuhade lai, dosti da kya matlab hai",
    "Tuhadia favorite hobbies kehdia hain",
    "Tuhada life da sabto memorable moment kehda hai",
    "Kya tuhanu cooking karna psnd hai",
    "😤😤menu dsoge kya chal reha he",
    "🤨",
    "Ik gl bola",
    "Tuhade ghar vich kon kon he",
    "Hi",
    "Hey",
    "Hui",
    "Bye",
    "Kithe ho???",
    "Kdd aaoge",
    "Haan, main tere naal ha 💪",
    "Dhanvaad boht boht! 🙌",
    "Boht khushi hoi tuhanu milke 😊🤝",
    "Theek ha, dhanvaad! 😄",
    "Tuhada swagat hai! 🙏🏼",
    "Kya main tuhadi madad kar sakdi han? 🤝",
    "Tuhadi madad karn lai main ithe han 💁‍♀️",
    "Eh boht romanchak hai! 😃🎉",
    "Ki tuhanh ek pasand hai? ❤️",
    "Main tuhanu bahut yaad kar rhu si😌💕",
    "Tusi mere sabto vdia dost ho 🤗👭",
    "Hamesha ehi sochda c! 💭",
    "Tuhade bina mera din adhura hai 😔💔",
]
